# Generated by Django 4.0.3 on 2022-04-10 14:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('measurement_meta', models.CharField(max_length=20)),
                ('value', models.FloatField()),
            ],
        ),
    ]
